config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/index'
  get 'users/edit'
  devise_for :users
  root :to => 'users#top'
  get 'books' => 'books#index'
  post 'books', to: 'books#create'
  get 'books/:id' => 'books#show', as:'book'
  get 'books/:id/edit' => 'books#edit', as:'edit_book'
  delete 'books/:id' => 'books#destroy', as:'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  validates :name,
  uniqueness: { case_sensitive: :false },
  length: { minimum: 2, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
	  devise_parameter_sanitizer.permit(:sign_, keys: [:name])
	end

	#def after_sign_inpath_for(resource)
	#	user_path(current_user)
	#end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		   redirect_to book_path(@book.id)
		else
			@books = Book.all
			render :index
		end
	end

	def index
		@book = Book.new
		@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private

	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>
	<div class="field">
		<%= f.label :title, "Title" %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :body, "Opinion" %>
		<%= f.text_area :body %>
	</div>
	<div><%= f.submit "Update Book"%></div>
<% end %>

<div><%= link_to "Show", book_path %></div>
<div>|</div>
<div><%= link_to "Back", books_path %></div>

app/views/books/index.html.erb
<div class="index-box">

	<div id="error">
		<% if @book.errors.any? %>
			<%= @book.errors.count %>error prohibited this obj from being saved:
			<% @book.errors.full_messages.each do |message| %>
				<%= message %>
			<% end %>
		<% end %>
	</div>


	<h2>New Book</h2>
		<%= form_for(@book) do |f| %>
			
			<label>Title</label>
			<%= f.text_field :title %>

			<label>Opinion</label>
			<%= f.text_area :body %>

			<%= f.submit "Create Book" %>

		<% end %>

	<h2>Books</h2>
	<table>
		<thead>
		<tr>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
		</thead>
		<tbody>
			<% @books.each do |book| %>


				<tb>
					<%= link_to book_path(book.id) do %>
					<%= book.title %>
					<% end %>
				</tb>
				<tb>
					<%= link_to book_path(book.id) do %>
					<%= book.body %>
					<% end %>
				</tb>
			<% end %>
		</tbody>
	</table>
</div>

app/views/books/show.html.erb
<div class="show_box">
<h2>Book detail</h2>

	<p><%= @book.title %></p>
	<p><%= @book.body %></p>
	<% if @book.user == current_user %>
		<%= link_to "Edit", edit_book_path %>
		<%= link_to "Destroy", destroy_book_path(@book), method: :delete %>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h2>Bookers</h2>

    <% if user_signed_in? %>
      <li class="">
        <!-- ↓以下のコードは、5章で正しいroutingに書き直します。 -->
        <%= link_to 'Home', "#" %>
      </li>
      <li class="">
        <%= link_to 'Users', "#" %>
      </li>
            <li class="">
        <%= link_to 'Books', books_path %>
      </li>
      <li class="">
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>

    <% else %>
      <li class="">
        <%= link_to "Home", "#" %>
      </li>
      <li class="">
        <%= link_to "About", "#" %>
      </li>
      <li class="">
        <%= link_to "sign up", new_user_registrations_path %>
      </li>
      <li class="">
        <%= link_to "login", new_user_session_path %>
      </li>
    <% end %>

    <%= yield %>
  </body>

  <fotter><p>CopyRight Infratop.inc</p></fotter>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>